### ISSUE TITLE
Cambiar String

### ISSUE THREAD

**Issue by apineiroandion** [cristianregueiromartinez69/ejemploIssue2#1]
https://github.com/cristianregueiromartinez69/ejemploIssue2/blob/6eeb0ba7d9f9aca76f69a356e1448a6465868719/src/Main.java#L3

Tenemos que hacer el contenido de string mas inclusivo, para que todes se sientan integrades

**Comment by cristianregueiromartinez69** [comment]
tienes razon, menudo error de novato
